# CLASSIFICATION
------------

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib as plt 

In [2]:
dataFrame = pd.read_csv("games.csv")

In [3]:
dataFrame.dropna(inplace=True)

In [4]:
dataFrame

id  rated    created_at  last_move_at  turns victory_status  \
0      TZJHLljE  False  1.504210e+12  1.504210e+12     13      outoftime   
1      l1NXvwaE   True  1.504130e+12  1.504130e+12     16         resign   
2      mIICvQHh   True  1.504130e+12  1.504130e+12     61           mate   
3      kWKvrqYL   True  1.504110e+12  1.504110e+12     61           mate   
4      9tXo1AUZ   True  1.504030e+12  1.504030e+12     95           mate   
...         ...    ...           ...           ...    ...            ...   
20053  EfqH7VVH   True  1.499791e+12  1.499791e+12     24         resign   
20054  WSJDhbPl   True  1.499698e+12  1.499699e+12     82           mate   
20055  yrAas0Kj   True  1.499698e+12  1.499698e+12     35           mate   
20056  b0v4tRyF   True  1.499696e+12  1.499697e+12    109         resign   
20057  N8G2JHGG   True  1.499643e+12  1.499644e+12     78           mate   

      winner increment_code       white_id  white_rating            black_id  \
0      white           15+2       bourgris          1500                a-00   
1      black           5+10           a-00          1322           skinnerua   
2      white           5+10         ischia          1496                a-00   
3      white           20+0  daniamurashov          1439        adivanov2009   
4      white           30+3      nik221107          1523        adivanov2009   
...      ...            ...            ...           ...                 ...   
20053  white          10+10        belcolt          1691            jamboger   
20054  black           10+0       jamboger          1233  farrukhasomiddinov   
20055  white           10+0       jamboger          1219        schaaksmurf3   
20056  white           10+0   marcodisogno          1360            jamboger   
20057  black           10+0       jamboger          1235               ffbob   

       black_rating                                              moves  \
0              1191  d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...   
1              1261  d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...   
2              1500  e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...   
3              1454  d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...   
4              1469  e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...   
...             ...                                                ...   
20053          1220  d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...   
20054          1196  d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...   
20055          1286  d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...   
20056          1227  e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...   
20057          1339  d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...   

      opening_eco                            opening_name  opening_ply  
0             D10        Slav Defense: Exchange Variation            5  
1             B00  Nimzowitsch Defense: Kennedy Variation            4  
2             C20   King's Pawn Game: Leonardis Variation            3  
3             D02  Queen's Pawn Game: Zukertort Variation            3  
4             C41                        Philidor Defense            5  
...           ...                                     ...          ...  
20053         A80                           Dutch Defense            2  
20054         A41                            Queen's Pawn            2  
20055         D00         Queen's Pawn Game: Mason Attack            3  
20056         B07                            Pirc Defense            4  
20057         D00         Queen's Pawn Game: Mason Attack            3  

[20058 rows x 16 columns]

In [5]:
dataFrame = dataFrame[["turns", "victory_status", "winner", "white_rating", "black_rating", "opening_ply", "rated"]]

In [6]:
dataFrame

turns victory_status winner  white_rating  black_rating  opening_ply  \
0         13      outoftime  white          1500          1191            5   
1         16         resign  black          1322          1261            4   
2         61           mate  white          1496          1500            3   
3         61           mate  white          1439          1454            3   
4         95           mate  white          1523          1469            5   
...      ...            ...    ...           ...           ...          ...   
20053     24         resign  white          1691          1220            2   
20054     82           mate  black          1233          1196            2   
20055     35           mate  white          1219          1286            3   
20056    109         resign  white          1360          1227            4   
20057     78           mate  black          1235          1339            3   

       rated  
0      False  
1       True  
2       True  
3       True  
4       True  
...      ...  
20053   True  
20054   True  
20055   True  
20056   True  
20057   True  

[20058 rows x 7 columns]

In [7]:
from sklearn import preprocessing

In [8]:
dataFrame1 = dataFrame.apply(preprocessing.LabelEncoder().fit_transform)

In [9]:
dataFrame21 = dataFrame1[["victory_status"]]
dataFrame22 = dataFrame[["winner"]]

In [10]:
oneHotEncoder = preprocessing.OneHotEncoder()

In [11]:
dataFrame23 = oneHotEncoder.fit_transform(dataFrame21).toarray()
dataFrame24 = oneHotEncoder.fit_transform(dataFrame22).toarray()

In [12]:
data1 = pd.DataFrame(data=dataFrame23, index=range(20058), columns=[["outoftime", "resign", "mate", "draw"]])
data2 = pd.DataFrame(data=dataFrame24, index=range(20058), columns=[["white", "black", "draw"]])
data3 = pd.concat([data1, data2], axis=1)
data4 = pd.concat([data3, dataFrame.iloc[:, [0, 3, 4, 5]]], axis=1)
data5 = pd.concat([data4, dataFrame.iloc[:, 6]], axis=1)

In [13]:
data5

(outoftime,)  (resign,)  (mate,)  (draw,)  (white,)  (black,)  (draw,)  \
0               0.0        0.0      1.0      0.0       0.0       0.0      1.0   
1               0.0        0.0      0.0      1.0       1.0       0.0      0.0   
2               0.0        1.0      0.0      0.0       0.0       0.0      1.0   
3               0.0        1.0      0.0      0.0       0.0       0.0      1.0   
4               0.0        1.0      0.0      0.0       0.0       0.0      1.0   
...             ...        ...      ...      ...       ...       ...      ...   
20053           0.0        0.0      0.0      1.0       0.0       0.0      1.0   
20054           0.0        1.0      0.0      0.0       1.0       0.0      0.0   
20055           0.0        1.0      0.0      0.0       0.0       0.0      1.0   
20056           0.0        0.0      0.0      1.0       0.0       0.0      1.0   
20057           0.0        1.0      0.0      0.0       1.0       0.0      0.0   

       turns  white_rating  black_rating  opening_ply  rated  
0         13          1500          1191            5  False  
1         16          1322          1261            4   True  
2         61          1496          1500            3   True  
3         61          1439          1454            3   True  
4         95          1523          1469            5   True  
...      ...           ...           ...          ...    ...  
20053     24          1691          1220            2   True  
20054     82          1233          1196            2   True  
20055     35          1219          1286            3   True  
20056    109          1360          1227            4   True  
20057     78          1235          1339            3   True  

[20058 rows x 12 columns]

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train, x_test, y_train, y_test = train_test_split(data5.iloc[:, :-1], data5.iloc[:, -1:], test_size = 1/3, random_state = 0)

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
sc = StandardScaler()

In [18]:
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

## 01 - LOGISTIC REGRESSION
-------------

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
# solver : ("newton_cg", "lbfgs", "liblinear", "sag", "saga") default = "lbfgs"
# random_state default: None

In [21]:
log_reg = LogisticRegression(random_state=0, solver="lbfgs")

In [22]:
log_reg.fit(X_train, y_train)

C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression(random_state=0)

In [23]:
y_pred = log_reg.predict(X_test)

In [24]:
y_pred

array([ True,  True,  True, ...,  True,  True,  True])

In [25]:
y_test

rated
9870   False
14355   True
10069   True
5951    True
9130   False
...      ...
7807    True
15140   True
4954   False
17920   True
15383   True

[6686 rows x 1 columns]

In [26]:
from sklearn.metrics import confusion_matrix

In [27]:
cm = confusion_matrix(y_test, y_pred)

In [28]:
print(cm)

[[   0 1275]
 [   0 5411]]


In [29]:
from sklearn.model_selection import cross_val_score

In [30]:
success = cross_val_score(estimator=log_reg, X=X_train, y=y_train, cv=4)

C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expe

In [31]:
print("Average success of model: ", success.mean())

Average success of model:  0.8034699371821717


In [32]:
print("Average standard deviation of model: ", success.std())

Average standard deviation of model:  0.0


## 02 - K-NN
---------------

In [33]:
from sklearn.neighbors import KNeighborsClassifier

In [34]:
# n_neighbors default = 5
# weights = ("uniform", "distance") default = "uniform"
# metric default = "minkowski"

In [35]:
knn = KNeighborsClassifier(n_neighbors=18, weights="uniform", metric="minkowski")

In [36]:
knn.fit(X_train, y_train)

C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=18)

In [37]:
y_pred = knn.predict(X_test)

In [38]:
from sklearn.metrics import confusion_matrix

In [39]:
cm = confusion_matrix(y_pred, y_test)

In [40]:
print(cm)

[[  77   71]
 [1198 5340]]


In [41]:
from sklearn.model_selection import cross_val_score

In [42]:
success = cross_val_score(estimator=knn, X=X_train, y=y_train, cv=4)

C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was pas

In [43]:
print("Average success of model: ", success.mean())

Average success of model:  0.8076577924020341


In [44]:
print("Average standard deviation of model: ", success.std())

Average standard deviation of model:  0.0010144077150950207


## 03 - SVM
----------------

In [45]:
from sklearn.svm import SVC

In [46]:
# kernel: ("rbf", "poly", "linear", "sigmoid", "precomputed") default: "rbf"
# degree default: "2"
# gamma: ("auto", "scale") default: ("scale")

In [47]:
svc = SVC(kernel="rbf", gamma="scale")

In [48]:
svc.fit(X_train, y_train)

C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC()

In [49]:
y_pred = svc.predict(X_test)

In [50]:
y_pred

array([ True,  True,  True, ...,  True,  True,  True])

In [51]:
from sklearn.metrics import confusion_matrix

In [52]:
cm = confusion_matrix(y_pred, y_test)

In [53]:
print(cm)

[[  26    6]
 [1249 5405]]


In [54]:
from sklearn.model_selection import cross_val_score

In [55]:
success = cross_val_score(estimator=svc, X=X_train, y=y_train, cv=4)

C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expe

In [56]:
print("Average success of model: ", success.mean())

Average success of model:  0.8073586598863296


In [57]:
print("Average standard deviation of model: ", success.std())

Average standard deviation of model:  0.0008460745213120572


## 04 - NAVIE BAYES
-----------------

In [58]:
from sklearn.naive_bayes import GaussianNB

In [59]:
gnb = GaussianNB()

In [60]:
gnb.fit(X_train, y_train)

C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


GaussianNB()

In [61]:
y_pred = gnb.predict(X_test)

In [62]:
y_pred

array([ True,  True,  True, ...,  True,  True, False])

In [63]:
from sklearn.metrics import confusion_matrix

In [64]:
cm = confusion_matrix(y_pred, y_test)

In [65]:
print(cm)

[[  79  236]
 [1196 5175]]


In [66]:
from sklearn.model_selection import cross_val_score

In [67]:
success = cross_val_score(estimator=gnb, X=X_train, y=y_train, cv=4)

C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expe

In [68]:
print("Average success of model: ", success.mean())

Average success of model:  0.7799880346993718


In [69]:
print("Average standard deviation of model: ", success.std())

Average standard deviation of model:  0.004306365554558198


## 05 - DECISION TREE
-----------

In [70]:
from sklearn.tree import DecisionTreeClassifier

In [71]:
# criterion = ("entropy", "gini") default = "gini"
# splitter = ("best", "random") default = "best"

In [72]:
dct = DecisionTreeClassifier(criterion="gini")

In [73]:
dct.fit(X_train, y_train)

DecisionTreeClassifier()

In [74]:
y_pred = dct.predict(X_test)

In [75]:
y_pred

array([ True,  True,  True, ..., False,  True,  True])

In [76]:
from sklearn.metrics import confusion_matrix

In [77]:
cm = confusion_matrix(y_pred, y_test)

In [78]:
print(cm)

[[ 560  806]
 [ 715 4605]]


In [79]:
from sklearn.model_selection import cross_val_score

In [80]:
success = cross_val_score(estimator=dct, X=X_train, y=y_train, cv=4)

In [81]:
print("Average success of model: ", success.mean())

Average success of model:  0.7645827101405923


In [82]:
print("Average standard deviation of model: ", success.std())

Average standard deviation of model:  0.0027415947920764985


## 06 - RANDOM FOREST
------------

In [83]:
from sklearn.ensemble import RandomForestClassifier

In [84]:
# n_estimators default = 100
# criterion = ("entropy", "gini") default = "gini"

In [85]:
rft = RandomForestClassifier(n_estimators=1000, criterion="gini")

In [86]:
rft.fit(X_train, y_train)

<ipython-input-86-c46114764760>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rft.fit(X_train, y_train)


RandomForestClassifier(n_estimators=1000)

In [87]:
y_pred = rft.predict(X_test)

In [88]:
y_pred

array([ True,  True,  True, ..., False,  True,  True])

In [89]:
from sklearn.metrics import confusion_matrix

In [90]:
cm = confusion_matrix(y_pred, y_test)

In [91]:
print(cm)

[[ 425  160]
 [ 850 5251]]


In [92]:
from sklearn.model_selection import cross_val_score

In [93]:
success = cross_val_score(estimator=rft, X=X_train, y=y_train, cv=4)

C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\model_selection\_validation.py:598: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\model_selection\_validation.py:598: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\model_selection\_validation.py:598: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\90545\anaconda3\envs\data science\lib\site-packages\sklearn\model_s

In [94]:
print("Average success of model: ", success.mean())

Average success of model:  0.838991923422076


In [95]:
print("Average standard deviation of model: ", success.std())

Average standard deviation of model:  0.003452195299905393
